---
title: "test.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

```{r}
activities <- tribble(~link, ~description, ~time,
                      "../../../slides/xaringan.html#yourturn1", "Season some slides with remark.js salt", "10:00 minutes",
                      "../../../slides/xaringan.html#yourturn2", "Fatten up your slides with some R code chunks (+ knitr butter)", "05:00 minutes",
                      "../../../slides/xaringan.html#yourturn3", "Add some acid to your slides with images", "08:00 minutes",
                      "../../../slides/xaringan.html#yourturn4", "Raise the heat on your slides by changing themes", "03:00 minutes",
                      "../../../slides/xaringan.html#yourturn5", "Serve your slides by publishing them online", "05:00 minutes")

activities %>% 
  mutate(activity = cell_spec(glue::glue('{emo::ji("heavy_plus_sign")} Your turn #{
                                          stringr::str_sub(
                                                            htmltools::htmlEscape(link, attribute = TRUE),
                                          start = -1)}: {description}'), 
                           "html", 
                           link = link),
         time = glue::glue('{emo::ji("clock")} {time}')
         ) %>%
  select(Activity = activity, Time = time) %>% 
  kable("html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "condensed")) 
```